### ISSUE TITLE
Define the power switch IC

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/edc-power-adapter#2]
Some requirements:

* Single or dual channel (1 or 2 input(s)/output(s))
* 3.3 V enable signal (on/off)
* Max. output current >= 1000 mA
* Max. input voltage >= 10 V
* Overcurrent protection
* Overvoltage protection
* Temperature grade: Automotive (-40 to 125 ºC)

**Comment by YanAzer** [comment]
First options found:

1. [NCV8452STT3G](https://br.mouser.com/ProductDetail/ON-Semiconductor/NCV8452STT3G?qs=8%252BXDBfnGdBworrfSDzzDIg%3D%3D)
2. [ITS4200SMENHUMA1](https://br.mouser.com/ProductDetail/Infineon-Technologies/ITS4200SMENHUMA1?qs=%2Fha2pyFadujXVLwr9i%252B%252Bd%252BhSUyYHPbAjs3H%252ByYRcbD6SYbrfUguDmn%2FVUSizVqCT)
3. [TPS1H000AQDGNRQ1](https://br.mouser.com/ProductDetail/Texas-Instruments/TPS1H000AQDGNRQ1?qs=%2Fha2pyFaduhE2VdeOckTbjSrI%2FUVJ07hWpxuHYOVZyYpnpmA70ltIQ%3D%3D)
4. [ISP762TFUMA1](https://br.mouser.com/ProductDetail/Infineon-Technologies/ISP762TFUMA1?qs=OwbwYO03UsKtW8epmS5q%252Bw%3D%3D) **Input turn-on threshold voltage: 2.2V?**

If a lower Max. input voltage be considered (like 5.5V) there will be much more options for the power switch, most of the ICs with Max. input voltage >= 10 V and encapsulated protection require minimum 5.5V to operate normally.

**Comment by mgm8** [comment]
@YanAzer can you check this one: [TPS22919-Q1](https://www.ti.com/product/TPS22919-Q1)?

**Comment by YanAzer** [comment]
@mgm8 thanks, i saw your sugestion and it seens to be the simplest solution.
I also found some other ones:

1. [TPS2065-Q1](https://www.ti.com/product/TPS2065-Q1?keyMatch=TPS2065-Q1&tisearch=Search-EN-everything&usecase=GPN#product-details)
2. [NCV8450ASTT3G](https://www.digikey.com/product-detail/en/on-semiconductor/NCV8450ASTT3G/NCV8450ASTT3GOSCT-ND/4927906)

I think **TPS2065-Q1** is a more suitable solution because has undevoltage and overcurrent protection, the function "Fault Report" can be ignored if not used, the only downside is the maximum voltage operation 5.5V. While **NCV8450ASTT3G** has a larger voltage operation (4.5V ~ 45V) and overvoltage protection, i didn't find the enable voltage on the IN pin on the datasheet. Looks like most higher power switches with minimum 5.5V operation has overvoltage protection, but i don't think this will be a big concern for us.

**Comment by YanAzer** [comment]
@mgm8 i also found other option and that has overvoltage protection, this was one of the only ICs found that could give this feature with minimum operation voltage of 4.5V:

* [VN5E160ASTR-E](https://www.st.com/content/st_com/en/products/automotive-analog-and-power/high-and-low-side-drivers-switches/high-side-switches/vn5e160as-e.html)

Unfortunately it seems the typical operation voltage is 13V, way above your application that is ~5V.

**Comment by mgm8** [comment]
@YanAzer the TPS2065-Q1 has a thermal pad, which difficults a bit the assembly process of the board. Also, the TPS2065-Q1 has two separated inputs with a single enable signal. From this family, the best model would be the TPS2062-Q1, with a single input and two separated enable signals.

I think we can choose the [TPS22919-Q1](https://www.ti.com/product/TPS22919-Q1) for now.
